//
// Created by ilya on 27.10.16.
//

#ifndef MIPT_SEMINARS_LECTURES_2_ND_COURSE_THREAD_POOL_H
#define MIPT_SEMINARS_LECTURES_2_ND_COURSE_THREAD_POOL_H

#endif //MIPT_SEMINARS_LECTURES_2_ND_COURSE_THREAD_POOL_H
